name: Test Laravel App with PostGIS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-3.3
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pdo, pdo_pgsql
          tools: composer
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction
      - name: install npm dependencies
        run: npm i
      - name: build frontend assets
        run: npm run build

      - name: Configure .env.testing for PostgreSQL
        run: |
          sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=pgsql/' .env.testing
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env.testing
          sed -i 's/DB_PORT=.*/DB_PORT=5432/' .env.testing
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=laravel/' .env.testing
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=postgres/' .env.testing
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=password/' .env.testing

      - name: debug env
        run: cat .env.testing
      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..15}; do
            pg_isready -h 127.0.0.1 -p 5432 -U postgres && break
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: composer run test
